/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/apijsonapi';
export * from './apis/biz-album-api';
export * from './apis/biz-catalog-api';
export * from './apis/biz-media-api';
export * from './apis/sys-auth-api';
export * from './apis/sys-cache-api';
export * from './apis/sys-code-gen-api';
export * from './apis/sys-code-gen-config-api';
export * from './apis/sys-config-api';
export * from './apis/sys-const-api';
export * from './apis/sys-database-api';
export * from './apis/sys-dict-data-api';
export * from './apis/sys-dict-type-api';
export * from './apis/sys-enum-api';
export * from './apis/sys-file-api';
export * from './apis/sys-job-api';
export * from './apis/sys-log-diff-api';
export * from './apis/sys-log-ex-api';
export * from './apis/sys-log-op-api';
export * from './apis/sys-log-vis-api';
export * from './apis/sys-menu-api';
export * from './apis/sys-message-api';
export * from './apis/sys-notice-api';
export * from './apis/sys-oauth-api';
export * from './apis/sys-online-user-api';
export * from './apis/sys-open-access-api';
export * from './apis/sys-org-api';
export * from './apis/sys-plugin-api';
export * from './apis/sys-pos-api';
export * from './apis/sys-print-api';
export * from './apis/sys-region-api';
export * from './apis/sys-role-api';
export * from './apis/sys-server-api';
export * from './apis/sys-sms-api';
export * from './apis/sys-tenant-api';
export * from './apis/sys-user-api';
export * from './apis/sys-wechat-api';
export * from './apis/sys-wechat-pay-api';
export * from './apis/sys-wechat-user-api';
export * from './apis/sys-wx-open-api';

