/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysUser } from './sys-user';
import { YesNoEnum } from './yes-no-enum';
import {
    SysUser,YesNoEnum,
} from ".";

/**
 * 
 *
 * @export
 * @interface AddConfigInput
 */
export interface AddConfigInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AddConfigInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof AddConfigInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    createUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof AddConfigInput
     */
    createUser?: SysUser;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    updateUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof AddConfigInput
     */
    updateUser?: SysUser;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof AddConfigInput
     */
    isDelete?: boolean;

    /**
     * 名称
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    name: string;

    /**
     * 编码
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    code?: string | null;

    /**
     * 属性值
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    value?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof AddConfigInput
     */
    sysFlag?: YesNoEnum;

    /**
     * 分组编码
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    groupCode?: string | null;

    /**
     * 排序
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    orderNo?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    remark?: string | null;
}
