/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysFile } from './sys-file';
import {
    SysFile,
} from ".";

/**
 * 分类输出参数
 *
 * @export
 * @interface BizCatalogOutput
 */
export interface BizCatalogOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof BizCatalogOutput
     */
    id?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof BizCatalogOutput
     */
    name?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof BizCatalogOutput
     */
    desc?: string | null;

    /**
     * 图标
     *
     * @type {string}
     * @memberof BizCatalogOutput
     */
    logo?: string | null;

    /**
     * @type {SysFile}
     * @memberof BizCatalogOutput
     */
    logoAttachment?: SysFile;

    /**
     * 排序
     *
     * @type {number}
     * @memberof BizCatalogOutput
     */
    sort?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof BizCatalogOutput
     */
    createUserName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof BizCatalogOutput
     */
    updateUserName?: string | null;
}
