/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 专辑分页查询输入参数
 *
 * @export
 * @interface BizAlbumInput
 */
export interface BizAlbumInput {

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof BizAlbumInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof BizAlbumInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    descStr?: string | null;

    /**
     * 关键字查询
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    searchKey?: string | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    name?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    desc?: string | null;

    /**
     * 图标
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    logo?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    createUserName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof BizAlbumInput
     */
    updateUserName?: string | null;
}
