/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DbColumnInput } from './db-column-input';
 /**
 * 
 *
 * @export
 * @interface DbTableInput
 */
export interface DbTableInput {

    /**
     * @type {string}
     * @memberof DbTableInput
     */
    configId?: string | null;

    /**
     * @type {string}
     * @memberof DbTableInput
     */
    tableName?: string | null;

    /**
     * @type {string}
     * @memberof DbTableInput
     */
    description?: string | null;

    /**
     * @type {Array<DbColumnInput>}
     * @memberof DbTableInput
     */
    dbColumnInfoList?: Array<DbColumnInput> | null;
}
