/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 删除消息模板
 *
 * @export
 * @interface DeleteMessageTemplateInput
 */
export interface DeleteMessageTemplateInput {

    /**
     * 订阅模板Id
     *
     * @type {string}
     * @memberof DeleteMessageTemplateInput
     */
    templateId: string;
}
