/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface DeleteDbColumnInput
 */
export interface DeleteDbColumnInput {

    /**
     * @type {string}
     * @memberof DeleteDbColumnInput
     */
    configId?: string | null;

    /**
     * @type {string}
     * @memberof DeleteDbColumnInput
     */
    tableName?: string | null;

    /**
     * @type {string}
     * @memberof DeleteDbColumnInput
     */
    dbColumnName?: string | null;
}
