/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
import {
    StatusEnum,
} from ".";

/**
 * 
 *
 * @export
 * @interface DictTypeInput
 */
export interface DictTypeInput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof DictTypeInput
     */
    id: number;

    /**
     * @type {StatusEnum}
     * @memberof DictTypeInput
     */
    status?: StatusEnum;
}
