/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 枚举类型输出参数
 *
 * @export
 * @interface EnumTypeOutput
 */
export interface EnumTypeOutput {

    /**
     * 枚举类型描述
     *
     * @type {string}
     * @memberof EnumTypeOutput
     */
    typeDescribe?: string | null;

    /**
     * 枚举类型名称
     *
     * @type {string}
     * @memberof EnumTypeOutput
     */
    typeName?: string | null;

    /**
     * 枚举类型备注
     *
     * @type {string}
     * @memberof EnumTypeOutput
     */
    typeRemark?: string | null;
}
