/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 枚举实体
 *
 * @export
 * @interface EnumEntity
 */
export interface EnumEntity {

    /**
     * 枚举的描述
     *
     * @type {string}
     * @memberof EnumEntity
     */
    describe?: string | null;

    /**
     * 枚举名称
     *
     * @type {string}
     * @memberof EnumEntity
     */
    name?: string | null;

    /**
     * 枚举对象的值
     *
     * @type {number}
     * @memberof EnumEntity
     */
    value?: number;
}
