/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface FileOutput
 */
export interface FileOutput {

    /**
     * Id
     *
     * @type {number}
     * @memberof FileOutput
     */
    id?: number;

    /**
     * 提供者
     *
     * @type {string}
     * @memberof FileOutput
     */
    provider?: string | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof FileOutput
     */
    name?: string | null;

    /**
     * URL
     *
     * @type {string}
     * @memberof FileOutput
     */
    url?: string | null;

    /**
     * 大小
     *
     * @type {string}
     * @memberof FileOutput
     */
    sizeKb?: string | null;

    /**
     * 后缀
     *
     * @type {string}
     * @memberof FileOutput
     */
    suffix?: string | null;

    /**
     * 路径
     *
     * @type {string}
     * @memberof FileOutput
     */
    filePath?: string | null;

    /**
     * 文件名称
     *
     * @type {string}
     * @memberof FileOutput
     */
    fileName?: string | null;
}
