/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 生成网页授权Url
 *
 * @export
 * @interface GenAuthUrlInput
 */
export interface GenAuthUrlInput {

    /**
     * RedirectUrl
     *
     * @type {string}
     * @memberof GenAuthUrlInput
     */
    redirectUrl?: string | null;

    /**
     * Scope
     *
     * @type {string}
     * @memberof GenAuthUrlInput
     */
    scope?: string | null;
}
