/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 用户登录参数
 *
 * @export
 * @interface LoginInput
 */
export interface LoginInput {

    /**
     * 账号
     *
     * @type {string}
     * @memberof LoginInput
     * @example admin
     */
    account: string;

    /**
     * 密码
     *
     * @type {string}
     * @memberof LoginInput
     * @example 123456
     */
    password: string;

    /**
     * 验证码Id
     *
     * @type {number}
     * @memberof LoginInput
     */
    codeId?: number;

    /**
     * 验证码
     *
     * @type {string}
     * @memberof LoginInput
     */
    code?: string | null;
}
