/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountTypeEnum } from './account-type-enum';
 /**
 * 用户登录信息
 *
 * @export
 * @interface LoginUserOutput
 */
export interface LoginUserOutput {

    /**
     * 用户id
     *
     * @type {number}
     * @memberof LoginUserOutput
     */
    id?: number;

    /**
     * 账号名称
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    account?: string | null;

    /**
     * 真实姓名
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    realName?: string | null;

    /**
     * @type {AccountTypeEnum}
     * @memberof LoginUserOutput
     */
    accountType?: AccountTypeEnum;

    /**
     * 头像
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    avatar?: string | null;

    /**
     * 个人简介
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    introduction?: string | null;

    /**
     * 地址
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    address?: string | null;

    /**
     * 电子签名
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    signature?: string | null;

    /**
     * 机构Id
     *
     * @type {number}
     * @memberof LoginUserOutput
     */
    orgId?: number;

    /**
     * 机构名称
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    orgName?: string | null;

    /**
     * 机构类型
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    orgType?: string | null;

    /**
     * 职位名称
     *
     * @type {string}
     * @memberof LoginUserOutput
     */
    posName?: string | null;

    /**
     * 按钮权限集合
     *
     * @type {Array<string>}
     * @memberof LoginUserOutput
     */
    buttons?: Array<string> | null;
}
