/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface LoginPhoneInput
 */
export interface LoginPhoneInput {

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof LoginPhoneInput
     * @example admin
     */
    phone: string;

    /**
     * 验证码
     *
     * @type {string}
     * @memberof LoginPhoneInput
     * @example 123456
     */
    code: string;
}
