/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 消息类型枚举<br />&nbsp;消息 Info = 0<br />&nbsp;成功 Success = 1<br />&nbsp;警告 Warning = 2<br />&nbsp;错误 Error = 3<br />
 * @export
 * @enum {string}
 */
export enum MessageTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

