/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MessageTypeEnum } from './message-type-enum';
import {
    MessageTypeEnum,
} from ".";

/**
 * 
 *
 * @export
 * @interface MessageInput
 */
export interface MessageInput {

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof MessageInput
     */
    userId?: number;

    /**
     * 用户ID列表
     *
     * @type {Array<number>}
     * @memberof MessageInput
     */
    userIds?: Array<number> | null;

    /**
     * 消息标题
     *
     * @type {string}
     * @memberof MessageInput
     */
    title?: string | null;

    /**
     * @type {MessageTypeEnum}
     * @memberof MessageInput
     */
    messageType?: MessageTypeEnum;

    /**
     * 消息内容
     *
     * @type {string}
     * @memberof MessageInput
     */
    message?: string | null;
}
