/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 通知公告用户状态枚举<br />&nbsp;未读 UNREAD = 0<br />&nbsp;已读 READ = 1<br />
 * @export
 * @enum {string}
 */
export enum NoticeUserStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

