/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 通知公告状态枚举<br />&nbsp;草稿 DRAFT = 0<br />&nbsp;发布 PUBLIC = 1<br />&nbsp;撤回 CANCEL = 2<br />&nbsp;删除 DELETED = 3<br />
 * @export
 * @enum {string}
 */
export enum NoticeStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

