/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 通知公告状类型枚举<br />&nbsp;通知 NOTICE = 1<br />&nbsp;公告 ANNOUNCEMENT = 2<br />
 * @export
 * @enum {string}
 */
export enum NoticeTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

