/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 角色列表输出参数
 *
 * @export
 * @interface RoleOutput
 */
export interface RoleOutput {

    /**
     * Id
     *
     * @type {number}
     * @memberof RoleOutput
     */
    id?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof RoleOutput
     */
    name?: string | null;

    /**
     * 编码
     *
     * @type {string}
     * @memberof RoleOutput
     */
    code?: string | null;
}
