/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 授权角色机构
 *
 * @export
 * @interface RoleOrgInput
 */
export interface RoleOrgInput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof RoleOrgInput
     */
    id: number;

    /**
     * 数据范围
     *
     * @type {number}
     * @memberof RoleOrgInput
     */
    dataScope?: number;

    /**
     * 机构Id集合
     *
     * @type {Array<number>}
     * @memberof RoleOrgInput
     */
    orgIdList?: Array<number> | null;
}
