/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 授权角色菜单
 *
 * @export
 * @interface RoleMenuInput
 */
export interface RoleMenuInput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof RoleMenuInput
     */
    id: number;

    /**
     * 菜单Id集合
     *
     * @type {Array<number>}
     * @memberof RoleMenuInput
     */
    menuIdList?: Array<number> | null;
}
