/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 菜单Meta配置
 *
 * @export
 * @interface SysMenuMeta
 */
export interface SysMenuMeta {

    /**
     * 标题
     *
     * @type {string}
     * @memberof SysMenuMeta
     */
    title?: string | null;

    /**
     * 图标
     *
     * @type {string}
     * @memberof SysMenuMeta
     */
    icon?: string | null;

    /**
     * 是否内嵌
     *
     * @type {boolean}
     * @memberof SysMenuMeta
     */
    isIframe?: boolean;

    /**
     * 外链链接
     *
     * @type {string}
     * @memberof SysMenuMeta
     */
    isLink?: string | null;

    /**
     * 是否隐藏
     *
     * @type {boolean}
     * @memberof SysMenuMeta
     */
    isHide?: boolean;

    /**
     * 是否缓存
     *
     * @type {boolean}
     * @memberof SysMenuMeta
     */
    isKeepAlive?: boolean;

    /**
     * 是否固定
     *
     * @type {boolean}
     * @memberof SysMenuMeta
     */
    isAffix?: boolean;
}
