/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NoticeStatusEnum } from './notice-status-enum';
import { NoticeTypeEnum } from './notice-type-enum';
import { SysUser } from './sys-user';
 /**
 * 系统通知公告表
 *
 * @export
 * @interface SysNotice
 */
export interface SysNotice {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysNotice
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysNotice
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysNotice
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysNotice
     */
    createUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof SysNotice
     */
    createUser?: SysUser;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysNotice
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysNotice
     */
    updateUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof SysNotice
     */
    updateUser?: SysUser;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysNotice
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SysNotice
     */
    isDelete?: boolean;

    /**
     * 标题
     *
     * @type {string}
     * @memberof SysNotice
     */
    title: string;

    /**
     * 内容
     *
     * @type {string}
     * @memberof SysNotice
     */
    content: string;

    /**
     * @type {NoticeTypeEnum}
     * @memberof SysNotice
     */
    type?: NoticeTypeEnum;

    /**
     * 发布人Id
     *
     * @type {number}
     * @memberof SysNotice
     */
    publicUserId?: number;

    /**
     * 发布人姓名
     *
     * @type {string}
     * @memberof SysNotice
     */
    publicUserName?: string | null;

    /**
     * 发布机构Id
     *
     * @type {number}
     * @memberof SysNotice
     */
    publicOrgId?: number;

    /**
     * 发布机构名称
     *
     * @type {string}
     * @memberof SysNotice
     */
    publicOrgName?: string | null;

    /**
     * 发布时间
     *
     * @type {Date}
     * @memberof SysNotice
     */
    publicTime?: Date | null;

    /**
     * 撤回时间
     *
     * @type {Date}
     * @memberof SysNotice
     */
    cancelTime?: Date | null;

    /**
     * @type {NoticeStatusEnum}
     * @memberof SysNotice
     */
    status?: NoticeStatusEnum;
}
