/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 数据库表
 *
 * @export
 * @interface TableOutput
 */
export interface TableOutput {

    /**
     * 库定位器名
     *
     * @type {string}
     * @memberof TableOutput
     */
    configId?: string | null;

    /**
     * 表名（字母形式的）
     *
     * @type {string}
     * @memberof TableOutput
     */
    tableName?: string | null;

    /**
     * 实体名称
     *
     * @type {string}
     * @memberof TableOutput
     */
    entityName?: string | null;

    /**
     * 创建时间
     *
     * @type {string}
     * @memberof TableOutput
     */
    createTime?: string | null;

    /**
     * 更新时间
     *
     * @type {string}
     * @memberof TableOutput
     */
    updateTime?: string | null;

    /**
     * 表名称描述（功能名）
     *
     * @type {string}
     * @memberof TableOutput
     */
    tableComment?: string | null;
}
