/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 专辑更新输入参数
 *
 * @export
 * @interface UpdateBizAlbumInput
 */
export interface UpdateBizAlbumInput {

    /**
     * 名称
     *
     * @type {string}
     * @memberof UpdateBizAlbumInput
     */
    name?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof UpdateBizAlbumInput
     */
    desc?: string | null;

    /**
     * 图标
     *
     * @type {string}
     * @memberof UpdateBizAlbumInput
     */
    logo?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof UpdateBizAlbumInput
     */
    createUserName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof UpdateBizAlbumInput
     */
    updateUserName?: string | null;

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof UpdateBizAlbumInput
     */
    id: number;
}
