/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysTenant } from './sys-tenant';
import { SysUser } from './sys-user';
import {
    SysTenant,SysUser,
} from ".";

/**
 * 
 *
 * @export
 * @interface UpdateOpenAccessInput
 */
export interface UpdateOpenAccessInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof UpdateOpenAccessInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof UpdateOpenAccessInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    createUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof UpdateOpenAccessInput
     */
    createUser?: SysUser;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    updateUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof UpdateOpenAccessInput
     */
    updateUser?: SysUser;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof UpdateOpenAccessInput
     */
    isDelete?: boolean;

    /**
     * 绑定租户Id
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    bindTenantId?: number;

    /**
     * @type {SysTenant}
     * @memberof UpdateOpenAccessInput
     */
    bindTenant?: SysTenant;

    /**
     * @type {SysUser}
     * @memberof UpdateOpenAccessInput
     */
    bindUser?: SysUser;

    /**
     * 身份标识
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    accessKey: string;

    /**
     * 密钥
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    accessSecret: string;

    /**
     * 绑定用户Id
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    bindUserId: number;
}
