/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DbType } from './db-type';
import { StatusEnum } from './status-enum';
import { SysUser } from './sys-user';
import { TenantTypeEnum } from './tenant-type-enum';
import {
    DbType,StatusEnum,SysUser,TenantTypeEnum,
} from ".";

/**
 * 
 *
 * @export
 * @interface UpdateTenantInput
 */
export interface UpdateTenantInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof UpdateTenantInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof UpdateTenantInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof UpdateTenantInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof UpdateTenantInput
     */
    createUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof UpdateTenantInput
     */
    createUser?: SysUser;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof UpdateTenantInput
     */
    updateUserId?: number | null;

    /**
     * @type {SysUser}
     * @memberof UpdateTenantInput
     */
    updateUser?: SysUser;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof UpdateTenantInput
     */
    isDelete?: boolean;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof UpdateTenantInput
     */
    userId?: number;

    /**
     * 机构Id
     *
     * @type {number}
     * @memberof UpdateTenantInput
     */
    orgId?: number;

    /**
     * 主机
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    host?: string | null;

    /**
     * @type {TenantTypeEnum}
     * @memberof UpdateTenantInput
     */
    tenantType?: TenantTypeEnum;

    /**
     * @type {DbType}
     * @memberof UpdateTenantInput
     */
    dbType?: DbType;

    /**
     * 数据库连接
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    connection?: string | null;

    /**
     * 数据库标识
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    configId?: string | null;

    /**
     * 排序
     *
     * @type {number}
     * @memberof UpdateTenantInput
     */
    orderNo?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    remark?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof UpdateTenantInput
     */
    status?: StatusEnum;

    /**
     * 电子邮箱
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    email?: string | null;

    /**
     * 电话
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    phone?: string | null;

    /**
     * 租户名称
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    name: string;

    /**
     * 租管账号
     *
     * @type {string}
     * @memberof UpdateTenantInput
     */
    adminAccount: string;
}
