/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WechatUserInput
 */
export interface WechatUserInput {

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof WechatUserInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof WechatUserInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof WechatUserInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof WechatUserInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof WechatUserInput
     */
    descStr?: string | null;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof WechatUserInput
     */
    nickName?: string | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof WechatUserInput
     */
    phoneNumber?: string | null;
}
