/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface WechatPayOutput
 */
export interface WechatPayOutput {

    /**
     * OpenId
     *
     * @type {string}
     * @memberof WechatPayOutput
     */
    openId?: string | null;

    /**
     * 订单金额
     *
     * @type {number}
     * @memberof WechatPayOutput
     */
    total?: number;

    /**
     * 附加数据
     *
     * @type {string}
     * @memberof WechatPayOutput
     */
    attachment?: string | null;

    /**
     * 优惠标记
     *
     * @type {string}
     * @memberof WechatPayOutput
     */
    goodsTag?: string | null;
}
