/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 是否枚举<br />&nbsp;是 Y = 1<br />&nbsp;否 N = 2<br />
 * @export
 * @enum {string}
 */
export enum YesNoEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

